version: ~> 1.0

language: python

notifications:
  webhooks: https://coveralls.io/webhook

branches:
  only:
  - master
  - stable
  - docs
  - /^v\d+(\.\d+)+/

env:
  global:
    - CANONICAL_PYTHON="3.8"
    - CODECLIMATE=""
    - TWINE_USERNAME="dwhswenson"
    # TWINE_PASSWORD
    # AUTORELEASE_TOKEN
  matrix:
    - CONDA_PY=3.8
    - CONDA_PY=3.6
    - CONDA_PY=3.7

before_install:
  - echo "before install"
  - git fetch --tags

install:
  # we use conda to manage Python versions, but all the install is pip
  - source ./devtools/miniconda_install.sh
  - conda create --yes -n ops-cli-py${CONDA_PY} python=$CONDA_PY
  - source activate ops-cli-py${CONDA_PY}
  - pip install -e .
  - pip install -r ./devtools/tests_require.txt
  - pip list

script:
  - python -c "import paths_cli"
  - python autorelease_check.py --branch ${TRAVIS_BRANCH} --event ${TRAVIS_EVENT_TYPE} #--allow-patch-skip  # allow-patch-skip if there was a testpypi problem
  #- py.test -vv --cov=paths_cli --cov-report xml:cov.xml
  - py.test -vv --cov --cov-report xml:cov.xml

after_success:
  - COVERALLS_PARALLEL=true coveralls

import:
  - dwhswenson/autorelease:autorelease-travis.yml@v0.1.2
